import { project } from "../assets";

export const Topprojects = [
    {
        key: 0,
        image: project,
        title: "Project 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
    },
    {
        key: 1,
        image: project,
        title: "Project 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
    },
    {
        key: 2,
        image: project,
        title: "Project 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
    },
]

export const Allprojects = [
    {
        key: 0,
        image: project,
        Low_level: true,
        Desktop_apps: true,
        Frontend: true,
        title: "Project 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
    {
        key: 1,
        image: project,
        Low_level: true,
        Desktop_apps: true,
        Frontend: false,
        title: "Project 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: true,
    },
    {
        key: 2,
        image: project,
        Low_level: true,
        Desktop_apps: false,
        Frontend: false,
        title: "Project 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
    {
        key: 3,
        image: project,
        Low_level: false,
        Desktop_apps: false,
        Frontend: false,
        title: "Project 4",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: true,
    },
    {
        key: 4,
        image: project,
        Low_level: false,
        Desktop_apps: false,
        Frontend: true,
        title: "Project 5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
    {
        key: 5,
        image: project,
        Low_level: false,
        Desktop_apps: true,
        Frontend: true,
        title: "Project 6",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: true,
    },
    {
        key: 6,
        image: project,
        Low_level: false,
        Desktop_apps: true,
        Frontend: false,
        title: "Project 7",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
    {
        key: 7,
        image: project,
        Low_level: true,
        Desktop_apps: false,
        Frontend: true,
        title: "Project 8",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: true,
    },
    {
        key: 8,
        image: project,
        Low_level: true,
        Desktop_apps: true,
        Frontend: false,
        title: "Project 9",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
    {
        key: 9,
        image: project,
        Low_level: true,
        Desktop_apps: false,
        Frontend: false,
        title: "Project 10",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: true,
    },
    {
        key: 10,
        image: project,
        Low_level: false,
        Desktop_apps: false,
        Frontend: false,
        title: "Project 11",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et.",
        link: "#",
        hasWebsite: false,
    },
]